// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oaXUEGapRcCGqowHuDEpD8
// Component: hwjrDFXlhjSo
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import NavigationBar from "../../NavigationBar"; // plasmic-import: 2P7sajECr50s/component
import Button from "../../Button"; // plasmic-import: _eM8SB4QErat/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import ProjectCard from "../../ProjectCard"; // plasmic-import: TYimLntQf16_/component
import ContactSection from "../../ContactSection"; // plasmic-import: YtGQ5t_QmBzd/component
import Footer from "../../Footer"; // plasmic-import: jv_LgadY7Zhn/component
import { useScreenVariants as useScreenVariantsoyplvy8WjIzj } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Oyplvy8WjIZJ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: oaXUEGapRcCGqowHuDEpD8/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: hwjrDFXlhjSo/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: 5-uwJg7qmtlP/icon
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: 46f3XTocZ9SH/icon

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsoyplvy8WjIzj()
  });
  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />

        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />

        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />

        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />

        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
          />

          <Stack__
            as={"section"}
            data-plasmic-name={"intro"}
            data-plasmic-override={overrides.intro}
            hasGap={true}
            className={classNames(projectcss.all, sty.intro)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__eTwqY)}>
              <div
                data-plasmic-name={"mainTextContainer"}
                data-plasmic-override={overrides.mainTextContainer}
                className={classNames(projectcss.all, sty.mainTextContainer)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Hey there, Anna here \ud83d\udc4b"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qms3I
                  )}
                >
                  {"Web designer and product designer for hire."}
                </div>
              </div>
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                component={Link}
                href={"#about"}
                platform={"nextjs"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pqS2O
                  )}
                >
                  {"About me"}
                </div>
                <RightArrowIcon
                  className={classNames(projectcss.all, sty.svg__tcmUf)}
                  role={"img"}
                />
              </PlasmicLink__>
            </div>
            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames("__wab_instance", sty.button)}
            />
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"services"}
            data-plasmic-override={overrides.services}
            hasGap={true}
            className={classNames(projectcss.all, sty.services)}
            id={"Services"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__wKElt)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cShW7
                )}
                id={"services"}
              >
                {"Services"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__yGiv5
                )}
              >
                {"Embracing constraints to push the boundaries."}
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___1Ml3H)}
            >
              <div className={classNames(projectcss.all, sty.column___2BSq1)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__k53F0)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/uxDesignpng.png",
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3___7IKuC
                  )}
                >
                  {"UX/UI & Web \nDesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__guDgI
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__hBhXn)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__sfkCu)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/brushpng.png",
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__hm6Wu
                  )}
                >
                  {"Branding & visual \ndesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e9L42
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__qmvCi)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__rqcSk)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/programmingpng.png",
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__f0MRt
                  )}
                >
                  {"Web \ndevelopment"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xNvbf
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"work"}
            data-plasmic-override={overrides.work}
            hasGap={true}
            className={classNames(projectcss.all, sty.work)}
            id={"work"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__xiTwz)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zCo6
                )}
                id={"services"}
              >
                {"work"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__ynJiV
                )}
              >
                {"Privileged to work with on some amazing projects."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__cBx5D)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__n38As)}
              >
                <div className={classNames(projectcss.all, sty.column___5VSu)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__maJs7)}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__xB9F
                      )}
                      link={`/project-relaunch`}
                      title={"Project Relaunch"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__tjAhK)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__ummeS)}
                    delay={250}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard___1J9De
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: "/plasmic/beginners_guide_website_in_3_minutes/images/abstractBackgroundJpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1171,
                        aspectRatio: undefined
                      }}
                      link={`/website-redesign`}
                      title={"Website Redesign"}
                    />
                  </Reveal>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__odJp)}
              >
                <div className={classNames(projectcss.all, sty.column__xcrpq)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__kYkpg)}
                    delay={500}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__haXJs
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: "/plasmic/beginners_guide_website_in_3_minutes/images/abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorjpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                      link={`/premium-sass-design`}
                      title={"Premium Saas Design"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__vQpmu)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__xg5R1)}
                    delay={750}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__hpC25
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: "/plasmic/beginners_guide_website_in_3_minutes/images/blueAndOrangeAbstractBackgroundFreeVectorjpg.jpg",
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                      link={`/web-visual-design`}
                      title={"Web Visual Graphic Design"}
                    />
                  </Reveal>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            hasGap={true}
            className={classNames(projectcss.all, sty.about)}
            id={"about"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__zSHr5)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__faZ7
                )}
                id={"about"}
              >
                {"About Me"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___6PbD3)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__fnhsw
                )}
              >
                {"Bridging design and no-code."}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___5Vh8Z
                )}
              >
                {
                  "Anna is an award winning, web designer specialising in no-code solutions. With over 8 years of professional experience I've helped countless startups launch & grow their business."
                }
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__kTs5T)}>
              <div className={classNames(projectcss.all, sty.freeBox___6Xkt)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__e9FH)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___3IEuM)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "311px"
                        : "312px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/beginners_guide_website_in_3_minutes/images/studentGa473640711280Jpg.jpg",
                      fullWidth: 1280,
                      fullHeight: 853,
                      aspectRatio: undefined
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__wQw9Q)}
                    displayHeight={"312px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/beginners_guide_website_in_3_minutes/images/lukePetersB6JiNerWMz0Unsplashjpg.jpg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__uEgl1)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__y5YEs)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/benKoldeBs2Ba7T69MMUnsplashjpg.jpg",
                    fullWidth: 1920,
                    fullHeight: 2449,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__jms9)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__v7AB3)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/beginners_guide_website_in_3_minutes/images/danielKorpaiAUmq852V7IUnsplashjpg.jpg",
                    fullWidth: 1920,
                    fullHeight: 2400,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___0Gpkz)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qdHy0
                )}
              >
                {"TESTIMONIALS"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__fP7D3
                )}
              >
                {"Hear from the folks I've worked with."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__ihK7W)}>
              <div className={classNames(projectcss.all, sty.freeBox__a61A)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__m4Snk)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__buaVk)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ujzb8)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__txBjN)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__b1CCa)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___7AVVs)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__jEmlp)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___2RrNw)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__olqta
                      )}
                    >
                      {"Very experienced"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7FoAb
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__da5Zs)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__yO9X)}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__nDm0V)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/alexSuprunZHvM3XioHoEUnsplashjpg.jpg",
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__g8Vtp
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6MYJn
                          )}
                        >
                          {"Albert David"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__icdKl
                          )}
                        >
                          {"Marketing Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fxbXs)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pm0Sr)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__zGmVx)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___3RkE4)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__jAoBw)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__csQNe)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__xeE7Y)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__m9Cnj
                      )}
                    >
                      {"Very fast & skillful"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f17Rk
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___6SmEh
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__lym8B
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___6PC9M)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/christopherCampbellRDeoVtE7VOsUnsplashjpg.jpg",
                            fullWidth: 640,
                            fullHeight: 427,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hQfKs
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dIEfL
                          )}
                        >
                          {"Arolina"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pEol
                          )}
                        >
                          {"Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__g8Gta)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dWak2)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nzact)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0R4Mt
                      )}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___4SgQd)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__emG83)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__uqqVf)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__oltQz)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__zEcAl)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__t19Q4
                      )}
                    >
                      {"skilled communicator"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4JvAu
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__oaY3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gYvJa
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__hg0L8)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/courtneyCookTsZo17R3M0SUnsplashjpg.jpg",
                            fullWidth: 640,
                            fullHeight: 960,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___28MHu
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vT5J
                          )}
                        >
                          {"Firmona"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___032Ci
                          )}
                        >
                          {"Founder, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__jcYN)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rhZe1)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__z19Sp)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__yOgNp)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__yy7P5)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__sFwtR)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__m0MGp)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__gvvVk
                      )}
                    >
                      {"Great design skills"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s6Kls
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__dAv9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dmfJb
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__clqEs)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/beginners_guide_website_in_3_minutes/images/alexanderHippIEebWgY6LAUnsplashjpg.jpg",
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___3XUsf
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mcCyr
                          )}
                        >
                          {"Motherson"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vXtG1
                          )}
                        >
                          {"Design Lead, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <ContactSection
            data-plasmic-name={"contactSection"}
            data-plasmic-override={overrides.contactSection}
            className={classNames("__wab_instance", sty.contactSection)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "intro",
    "mainTextContainer",
    "h1",
    "link",
    "button",
    "services",
    "work",
    "about",
    "testimonials",
    "contactSection",
    "footer"
  ],

  navigationBar: ["navigationBar"],
  intro: ["intro", "mainTextContainer", "h1", "link", "button"],
  mainTextContainer: ["mainTextContainer", "h1"],
  h1: ["h1"],
  link: ["link"],
  button: ["button"],
  services: ["services"],
  work: ["work"],
  about: ["about"],
  testimonials: ["testimonials"],
  contactSection: ["contactSection"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    intro: makeNodeComponent("intro"),
    mainTextContainer: makeNodeComponent("mainTextContainer"),
    h1: makeNodeComponent("h1"),
    link: makeNodeComponent("link"),
    button: makeNodeComponent("button"),
    services: makeNodeComponent("services"),
    work: makeNodeComponent("work"),
    about: makeNodeComponent("about"),
    testimonials: makeNodeComponent("testimonials"),
    contactSection: makeNodeComponent("contactSection"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Anna.Design",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
